### ISSUE TITLE
-psm 

### ISSUE THREAD

**Issue by ecassar01** [thiagoalessio/tesseract-ocr-for-php#102]
I am trying to use the option -psm 1, but none of the psm options work.
It only works via command prompt and not php .
In php the image is scanned but only on the default psm 3
I am using version  3.05.01

$scanimage =  (new TesseractOCR($imagescan))    
 ->executable('C:/wamp/www/SRPODS/Tesseract-OCR/tesseract.exe')		 	 	 
->psm(1)
  ->run();

Thanks

**Comment by thiagoalessio** [comment]
Hello,

Could you please post the image you are trying to recognise?

And since you mentioned that it works on the command line, would be helpful to post the command+output you got on the command line (so that we can compare to the output from the php script)

**Comment by ecassar01** [comment]
Hello,

the command line is tessract 25.jpg -psm 1 out1

When I do this in php, it defaults to -psm 3 for all the psm numbers.

[out1.txt](https://github.com/thiagoalessio/tesseract-ocr-for-php/files/1557137/out1.txt)
![25](https://user-images.githubusercontent.com/34495634/33963549-64b77924-e0a9-11e7-8ae1-bf4c985b14a6.jpg)

**Comment by thiagoalessio** [comment]
Yes, it defaults to psm 3 because that is tesseract's default

$ tesseract --help-psm
Page segmentation modes:
  0    Orientation and script detection (OSD) only.
  1    Automatic page segmentation with OSD.
  2    Automatic page segmentation, but no OSD, or OCR.
  3    Fully automatic page segmentation, but no OSD. (Default)
  4    Assume a single column of text of variable sizes.
  5    Assume a single uniform block of vertically aligned text.
  ...

But you can set it before running:

<?php
...
(new TesseractOCR('img.png'))->psm(1)->run();

As explained here: https://github.com/thiagoalessio/tesseract-ocr-for-php#psm <https://github.com/thiagoalessio/tesseract-ocr-for-php#psm>
There is also an example on the unit tests: https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/59d511730468a6adcd6e84d4c56a124206d3fe75/tests/UnitTests.php#L86 <https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/59d511730468a6adcd6e84d4c56a124206d3fe75/tests/UnitTests.php#L86>
Have you tried that?

Please let me know if it worked ;D

Best,
Thiago

**Comment by thiagoalessio** [comment]
Yes, it defaults to psm 3 because that is tesseract's default

```bash
$ tesseract --help-psm
Page segmentation modes:
  0    Orientation and script detection (OSD) only.
  1    Automatic page segmentation with OSD.
  2    Automatic page segmentation, but no OSD, or OCR.
➤ 3    Fully automatic page segmentation, but no OSD. (Default)
  4    Assume a single column of text of variable sizes.
  5    Assume a single uniform block of vertically aligned text.
  ...
```

But you can set it before running:

```php
<?php
...
(new TesseractOCR('img.png'))->psm(1)->run();
```

As explained here: https://github.com/thiagoalessio/tesseract-ocr-for-php#psm

There is also an example on the unit tests: https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/59d511730468a6adcd6e84d4c56a124206d3fe75/tests/UnitTests.php#L86-L95

Have you tried that?

Please let me know if it worked ;D

**Comment by ecassar01** [comment]
Yes i have tried it like this

$scanimage = (new TesseractOCR($imagescan))
->executable('C:/wamp/www/SRPODS/Tesseract-OCR/tesseract.exe')
->psm(1)
->run();

and it displays like if I ran it like --psm(3).
so no it did not wok in php.

**Comment by thiagoalessio** [comment]
yeah, please just do the following so that we can debug the generated tesseract command:

```diff
  $scanimage = (new TesseractOCR($imagescan))
  ->executable('C:/wamp/www/SRPODS/Tesseract-OCR/tesseract.exe')
  ->psm(1)
- ->run();
+ ->buildCommand();
```

**Comment by ecassar01** [comment]
This is the script:
   echo  (new TesseractOCR('25.jpg'))
           ->executable('C:/wamp/www/SRPODS/Tesseract-OCR/tesseract.exe')	
		    ->psm(1)
            ->buildCommand();
		  // ->run();

this is the result
"C:/wamp/www/SRPODS/Tesseract-OCR/tesseract.exe" "25.jpg" stdout quiet -psm 1

**Comment by thiagoalessio** [comment]
hum, ok ... we can see that the PHP library added the `-psm 1` argument at the end ... what happens when you manually run such command on your terminal?

**Comment by ecassar01** [comment]
This is what is produced.



 

Regards,



Edwin Cassar | Group Technology Manager | SeaRoad Holdings Pty Ltd

The Tower, 52 Empress Road, Webb Dock, PORT MELBOURNE VIC 3207  
P 03 9644 4041 |  M 0409 599 892 | E e.cassar@searoad.net
<mailto:%20e.cassar@searoad.net>  
www.searoad.net <http://www.searoad.net/>  

 

All Services provided by the members of SeaRoad Holdings are subject to
SeaRoad Holdings' Conditions of Contract and Consignment Note (where
applicable), a copy of which is available on request or may be viewed
online at the SeaRoad's website at www.searoad.net
<http://www.searoad.net/> .
SeaRoad Holdings' Conditions of Contract exclude SeaRoad Holdings'
liability in certain circumstances and include indemnities which benefit
SeaRoad Holdings. 
This email may be confidential and/or privileged. Only the intended
recipient may access or use it. If you are not the intended recipient,
please delete this email and notify us promptly. 
We use virus scanning software but exclude all liability for viruses or
similar in any attachment.

**Comment by thiagoalessio** [comment]
strange thing I noticed, is that it added a `quiet` argument, which should only happen on tesseract version `3.03`, but you mentioned you are using `3.05.01`, correct? will investigate that on the meantime

**Comment by ecassar01** [comment]
Yes



 

Regards,



Edwin Cassar | Group Technology Manager | SeaRoad Holdings Pty Ltd

The Tower, 52 Empress Road, Webb Dock, PORT MELBOURNE VIC 3207  
P 03 9644 4041 |  M 0409 599 892 | E e.cassar@searoad.net
<mailto:%20e.cassar@searoad.net>  
www.searoad.net <http://www.searoad.net/>  

 

All Services provided by the members of SeaRoad Holdings are subject to
SeaRoad Holdings' Conditions of Contract and Consignment Note (where
applicable), a copy of which is available on request or may be viewed
online at the SeaRoad's website at www.searoad.net
<http://www.searoad.net/> .
SeaRoad Holdings' Conditions of Contract exclude SeaRoad Holdings'
liability in certain circumstances and include indemnities which benefit
SeaRoad Holdings. 
This email may be confidential and/or privileged. Only the intended
recipient may access or use it. If you are not the intended recipient,
please delete this email and notify us promptly. 
We use virus scanning software but exclude all liability for viruses or
similar in any attachment.

**Comment by thiagoalessio** [comment]
Well, seems clear that you are not getting the expected result because of that undesired `quiet` argument.

The library relies heavily on the format of the `--version` output, that might be the issue. But on the Windows environment I tested (AppVeyor) it worked correctly.

https://ci.appveyor.com/project/thiagoalessio/tesseract-ocr-for-php/build/1.0.110#L142

Would you mind to run the same command (`tesseract --version 2>&1`) on your environment and post the complete output?

**Comment by ecassar01** [comment]
Regards,



Edwin Cassar | Group Technology Manager | SeaRoad Holdings Pty Ltd

The Tower, 52 Empress Road, Webb Dock, PORT MELBOURNE VIC 3207  
P 03 9644 4041 |  M 0409 599 892 | E e.cassar@searoad.net
<mailto:%20e.cassar@searoad.net>  
www.searoad.net <http://www.searoad.net/>  

 

All Services provided by the members of SeaRoad Holdings are subject to
SeaRoad Holdings' Conditions of Contract and Consignment Note (where
applicable), a copy of which is available on request or may be viewed
online at the SeaRoad's website at www.searoad.net
<http://www.searoad.net/> .
SeaRoad Holdings' Conditions of Contract exclude SeaRoad Holdings'
liability in certain circumstances and include indemnities which benefit
SeaRoad Holdings. 
This email may be confidential and/or privileged. Only the intended
recipient may access or use it. If you are not the intended recipient,
please delete this email and notify us promptly. 
We use virus scanning software but exclude all liability for viruses or
similar in any attachment.

**Comment by ecassar01** [comment]
Hi,

 

I have installed the version 4 alpha and it works fine, so we can close
this issue.

 

Thanks for your support.

 

 

Regards,



Edwin Cassar | Group Technology Manager | SeaRoad Holdings Pty Ltd

The Tower, 52 Empress Road, Webb Dock, PORT MELBOURNE VIC 3207  
P 03 9644 4041 |  M 0409 599 892 | E e.cassar@searoad.net
<mailto:%20e.cassar@searoad.net>  
www.searoad.net <http://www.searoad.net/>  

 

All Services provided by the members of SeaRoad Holdings are subject to
SeaRoad Holdings' Conditions of Contract and Consignment Note (where
applicable), a copy of which is available on request or may be viewed
online at the SeaRoad's website at www.searoad.net
<http://www.searoad.net/> .
SeaRoad Holdings' Conditions of Contract exclude SeaRoad Holdings'
liability in certain circumstances and include indemnities which benefit
SeaRoad Holdings. 
This email may be confidential and/or privileged. Only the intended
recipient may access or use it. If you are not the intended recipient,
please delete this email and notify us promptly. 
We use virus scanning software but exclude all liability for viruses or
similar in any attachment.
