### ISSUE TITLE
How to identify multi-line text?

### ISSUE THREAD

**Issue by linxiaojialin** [thiagoalessio/tesseract-ocr-for-php#109]
### Expected behavior

Hello, I can only recognize a line of text in the middle of the picture with your frame. Can this frame recognize the multi-line text in a picture?
If so, how can I use it?

### Actual behavior

 .

### Steps to reproduce the behavior

 .

#### Environment

* **Operating system:**

        > Windows10

* **PHP version:**

        $ php 7.0.13

* **Tesseract version:**

        $ tesseract 3.05.00dev

* **tesseract-ocr-for-php version:**

        $ thiagoalessio/tesseract_ocr 2.2.0

**Comment by thiagoalessio** [comment]
Hello again @linxiaojialin ,

Thanks for taking the time to translate this issue, but I'm still not 100% sure if you are just asking a question or if there is an actual problem with the library.

If is just a question, the answer is **yes**, it can recognise multi-line text normally. You can get more info on Page Segmentation mode [here](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#using-different-page-segmentation-modes) or by running `tesseract --help-psm`.

But if is an actual issue, please post a an example picture that you are trying to recognise alongside the relevant PHP code snippet so that I can get a closer look to help you.

**Comment by thiagoalessio** [comment]
@linxiaojialin ping!

**Comment by thiagoalessio** [comment]
well, I assume you no longer have the problem so i'm closing the issue.
if that is not the case, please reopen this one (no need to create a new issue, just reopen the same)
