### ISSUE TITLE
Getting coordinate of text.

### ISSUE THREAD

**Issue by Claw12** [thiagoalessio/tesseract-ocr-for-php#111]
**how to get the coordinate of a text from image?**

I have used hocr but it doesn't give me coordinate.
Can anyone specify any solution to extract coordinate of each text ?

**Comment by thiagoalessio** [comment]
Hello @Claw12 

Could you please provide me the info requested on the [issue template](https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/.github/issue_template.md)? it appeared to you when you opened this issue. Otherwise it becomes very hard for me (or anyone) to help you out.

But if is this just a question, I would like to ask you to don't open issues. There is a more appropriate place to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help

**Comment by thiagoalessio** [comment]
I've noticed that you followed up there on Gitter, thanks!
