### ISSUE TITLE
Is there anyway t sending multiple images on 1 run

### ISSUE THREAD

**Issue by stccorp** [thiagoalessio/tesseract-ocr-for-php#195]
Is there anyway to  send multiple images on 1 run? I imagine  that it should be faster than running  many times

something like 
$files = ['file1.jpg','file2.jpg'];
 $data = (new TesseractOCR($files))
            ->run();

**Comment by gxgl** [comment]
Hi,

I think you can use something like
You have the array of files $files...
foreach ($files as &$file) {
   do whatever with the file...
}
Like $data = (new TesseractOCR($file))
...this is a non teste idea, but it is a variant.

BR,
George

Obțineți Outlook pentru Android<https://aka.ms/ghei36>

________________________________

**Comment by thiagoalessio** [comment]
@stccorp tesseract itself only accepts one image per command, and since this lib is just a wrapper around it, the same restrictions apply.

something else you can try is to combine all images into a single one ([example](https://stackoverflow.com/questions/3876299/merging-two-images-with-php)) and then send this merged image a single time to tesseract.
