### ISSUE TITLE
Can i extract text from a cell of table in image with this library?

### ISSUE THREAD

**Issue by hungdang6676** [thiagoalessio/tesseract-ocr-for-php#214]
I'm having a problem need to resolve that i'm having an image which contain a table is a list of students with 3 columns, i want to extract the text of the first column and last column of each row. But look like the library is returning wrong datas.....

Is there anyway to make sense or train the machine to know which cell to get value?

**Comment by thiagoalessio** [comment]
this library is just a wrapper around tesseract, so it can do anything you'd be able to do on tesseract directly.
https://github.com/tesseract-ocr/tessdoc/blob/f8dd4d1a259bbaa024e01127e9c1d6208d8bd236/ImproveQuality.md#tables-recognitions

closing this issue here, please reach out to tesseract folks directly for this kind of enquiry.
