### ISSUE TITLE
Can't read Data from img

### ISSUE THREAD

**Issue by qiang5062250** [thiagoalessio/tesseract-ocr-for-php#91]
don't read this website verifycode:
http://www.miitbeian.gov.cn/getVerifyCode?73
i try you  offer img is OK ,i need you help.please .

you can save this website verify code XXX.JPG

**Comment by thiagoalessio** [comment]
hehehe trying to break captchas my friend ;D
Using the issues of this repo is a bit out of scope, but here it goes:

Given the original picture:

![original](https://user-images.githubusercontent.com/190616/32463768-fceb201c-c33d-11e7-9a20-7fb1a2b4f477.jpeg)

**Cleaning**

You'll need to use imagemagick (or something similar) to clean up the picture noise before sending to tesseract.
That can be achieved by playing around with some filters (a sequence of modulate, contrast-stretch and gaussian-blur) in order to minimize (or even get rid of) the thin strokes that compromise text recognition, for example:
```bash
$ convert -colorspace gray -modulate 120 -contrast-stretch 10%x80% -modulate 140 -gaussian-blur 1 -contrast-stretch 5%x50% +repage -negate -gaussian-blur 4 -negate -modulate 130 original.jpeg clean.jpeg
```

would give you the following image:

![clean](https://user-images.githubusercontent.com/190616/32463841-3fe858f8-c33e-11e7-99a6-7a348cb49e93.jpeg)

**Recognizing**

Now pass the clean image to tesseract:

```php
echo (new TesseractOCR('clean.jpeg'))->run();
// outputs 655V,3A
```

There is an undesired comma (,) on the output, because the cleaning wasn't 100% perfect.
But since you know that this particular captcha is only formed of numbers and uppercase letters, you can give this hint to tesseract, making the recognition more effective:

```php
echo (new TesseractOCR('clean.jpeg'))->whitelist(range(0, 9), range('A', 'Z'))->run();
// outputs 655V3A
```

And there you have it ... But I have to tell you, it will not work everytime. So make sure you collect a large number of captchas from this source, build the best cleaning sequence of filters you can, and prepare your code to keep trying new captchas until it succeeds.

**Comment by qiang5062250** [comment]
thank you verymuch
