### ISSUE TITLE
How install?

### ISSUE THREAD

**Issue by nazuna1** [thiagoalessio/tesseract-ocr-for-php#94]
Hi, 

First, thank you for make it.

I installed program that tesseract 3.04.
And, composer installed, run command "composer install".
compose echo "Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."
I writed "require 'vendor/autoload.php';" in test.php first line.
But, Apache Server alerted HTTP 500 Error.

I first used Composer, and think I had the wrong installation.
please, help me this framework installation.

**Comment by thiagoalessio** [comment]
I've just published some fixes, please try using the fresh version `1.2.2`.

Also, if you are on Windows, I wrote a small wiki page to help with some common problems.
Please take a look at https://github.com/thiagoalessio/tesseract-ocr-for-php/wiki/FAQ-for-Windows-Users.

I hope the new release works for you, otherwise please feel free to reopen this issue ;D
